language: python

python:
  - "2.7"

services:
  - docker

sudo: false

branches:
  except:
  - master

before_install:
  - docker build -t ds-snippets .

script:
  - docker run --rm --name ds-snippets-test ds-snippets /bin/bash -c "py.test --verbose --cov=src src/*/*.py"

notifications:
  on_success: always
  email: false
  slack:
    secure: "ZwUwjMVMQ04v5Az9+zy3bhIepH/xgwb2Yr3Xw6dRwXjhyNLvM3OWDNVRDFfNXhw/pbWbmXSGNJpcmCPVFYAb6RzjyqlrLD2v+igJ4tbJ0ZBtSrOamQA9JorNINRN3x6MF0GHwQYbsfLJaZUIF6JKTJrGYoi6lFbEHh5y71iO0OuqbRT7iq2FQGQ/I1AK1zzXWFcPfUm7Q+vimFlGoOWuB5T0bRv7r1ISY3I8Py5bxBVeLtMnYeZoB6Z3UI5877pjDgrXxFNFx1DlMn1Q1rVEyK6Mj+A9KhfyDSCKjL9uBXqRv7HJ3TLfIWWb/yCwfKUAsjoYWDgReOIjqFTA+p3GunrVx75Ggiq41qLHTpoSSStLx2JSJXYHstTohuysGYNM4IEz1vuoIIwMDlApddPfgMDoSy7O8se7PHfgBrZDJxqSwGKbgAQlxSYJTrNixl+LxwlrTTOqfLqYCbz8yFY+vUaWpmdQEKmU2iP7mRspJrGzaXzXVKEYDD5qp7A5RQrhvIby68UKJn4XGS1ooGuvuT0TLbZFP8POvmcOZGobGFaraLd9Xx+gC8Pt6QnlndqtxX9GfBsmz1onCvnf96Dh4ZgBjCJBbtyiIq/E5v39nuJSq7KCc9B9lITWASVHgkpQxB8r5sMzfBy/UzovDWr498Hr37MzBsNdwN5C0rVzLEw="
